name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run Npm run deploy
      run: |
        npm install -g gatsby-cli
        npm run deploy
        
      
