name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run git configs
      run: |
          git config --global user.email "ahmedayman055g@gmail.com"
          git config --global user.name "CI pipeline user"
    - name: run npm run deploy
      run: |
        yarn
        npm run deploy
        
      
